resources:
#- subscriptions/ibm-cp-integration/cp4i_all_subscription.yaml
#- subscriptions/individual-subscriptions/aspera.yaml
#- subscriptions/individual-subscriptions/op-dashboard.yaml
#- subscriptions/individual-subscriptions/api-connect.yaml
#- subscriptions/individual-subscriptions/mq.yaml
#- subscriptions/individual-subscriptions/platform-nav.yaml
#- subscriptions/individual-subscriptions/eventstreams.yaml
#- subscriptions/individual-subscriptions/app-connect.yaml
#- subscriptions/individual-subscriptions/automation-foundation.yaml
#- subscriptions/individual-subscriptions/datapower.yaml
patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: "gitops.tier.layer=daffy"
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/daffy-gitops/gitops-main.git
    - op: add
      path: /spec/source/targetRevision
      value: master
