resources:
- namespaces/namespace_cp4i.yaml
- operatorgroup/operatorgroup.yaml
patches:
- target:
    group: argoproj.io
    kind: Application
    labelSelector: "gitops.tier.layer=daffy"
  patch: |-
    - op: add
      path: /spec/source/repoURL
      value: https://github.com/daffy-gitops/gitops-main.git
    - op: add
      path: /spec/source/targetRevision
      value: master
