apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4i
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    gitops.tier.layer: daffy
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source: # repoURL  and targetRevision populated by kustomize patches in 3-apps/kustomization.yaml
    path: gitops/cp4i
  syncPolicy:
    automated:
      prune: true
      selfHeal: true