apiVersion: integration.ibm.com/v1beta1
kind: AssetRepository
metadata:
    name: assetrepo
    namespace:  cp4i
spec:
    designerAIFeatures:
      enabled: true
    license:
      accept: true
      license: L-PNAA-C68928
    replicas: 1
    storage:
      assetDataVolume:
        class: "managed-nfs-storage"
      couchVolume:
        class: "ibmc-block-gold"
    version: 2021.4.1
