apiVersion: integration.ibm.com/v1beta2
kind: OperationsDashboardServiceBinding
metadata:
  name: apic-od-service-binding
spec:
  odNamespace: "cp4i"
  odInstanceName: "tracing"
  sourceInstanceName: "apic-min-gw"
  sourcePodName: "apic-min-gw-0"
  sourceSecretName: "icp4i-od-store-cred"
